version: '3.4'

services:
    php:
      build:
        context: ./docker/php-fpm
        dockerfile: Dockerfile
        args:
          USERID: "${USERID:-1000}"
          GROUPID: "${GROUPID:-1000}"
      volumes:
        - .:/var/www:delegated
      working_dir: /var/www
      user: appuser
      environment:
        - COMPOSER_MEMORY_LIMIT=-1
      ports:
        - "9000:9000"

    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
        - .:/var/www:delegated
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

volumes:
    db_data: {}

