version: '3.4'

services:
    php:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - .:/var/www:delegated
        working_dir: /var/www
        command: php-fpm
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        ports:
            - "9000:9000"

    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
        - .:/var/www:delegated
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    db_data: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
